# --- Application ---
spring.application.name=auth-service
spring.security.debug=true
logging.level.org.springframework.security=TRACE
spring.config.import=optional:file:.env
# --- JWT SIGNING (AUTH SERVICE ONLY) ---

#jwt.expiration-ms=${JWT_EXPIRATION}
jwt.expiration-ms=${JWT_EXPIRATION_MS:300000}
#jwt.expiration=${JWT_EXPIRATION}

jwt.private-key-location=classpath:private.key
jwt.public-key-location=classpath:public.key

# --- Server ---
server.port=${AUTH_SERVER:8082}
services.auth.url=${AUTH_SERVICE_URL}

# --- Database (H2) ---
spring.datasource.url=jdbc:h2:file:./data/authdb

#;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# --- H2 Console ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
