language-ui:
  build: ./language-ui
  container_name: language-ui
  restart: unless-stopped
  ports:
    - "4200:80"
  depends_on:
    - auth-service
    - audio-services
    - pronunciation-service

