services:
  pronunciation-service:
    build:
      context: ./pronounciation-service
    container_name: pronunciation-service
    restart: unless-stopped
    ports:
      - "8084:8084"

    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8084

      # H2 DB
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/prondb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:

      # CORS
      APP_CORS_ALLOWED_ORIGINS: http://localhost:4200

      # Whisper config (optional if you use it)
      WHISPER_MODEL_PATH: /models/ggml-base.bin
      WHISPER_LANGUAGE: sw

    volumes:
      - pron_data:/data
      - ./models:/models   # 👈 mount your whisper model

    depends_on:
      - audio-services