spring.application.name=pronunciation-service
server.port=${PRONUNCIATION_SERVER_PORT:8084}
#whisper
whisper.cli.path=C:/Users/kokob/whisper.cpp-master/build/bin/Release/whisper-cli.exe
whisper.model.path=C:/Users/kokob/whisper.cpp-master/models/ggml-base.bin
whisper.language=sw
services.auth.url=${AUTH_SERVICE_URL:http://auth-service:8082}
services.audio.url=${AUDIO_SERVICE_URL:http://audio-services:8083}
services.pronunciation.url=${PRONUNCIATION_SERVICE_URL:http://pronunciation-service:8084}

spring.datasource.url=${PRONUNCIATION_DB_URL:jdbc:h2:file:./data/pronunciationdb}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${PRONUNCIATION_DB_USERNAME:sa}
spring.datasource.password=${PRONUNCIATION_DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

minio.url=${MINIO_URL:http://minio:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket.word=${MINIO_WORD_BUCKET:wordbucket}
minio.bucket.sentence=${MINIO_SENTENCE_BUCKET:sentencebucket}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWKS_URI:http://auth-service:8082/.well-known/jwks.json}
vosk.model-path=C:/Users/kokob/vox/vosk-model-small-en-us-0.15