spring.application.name=audio-services
server.port=8083
#Whisper
whisper.cli.path=C:/Users/kokob/whisper.cpp-master/build/bin/Release/whisper-cli.exe
whisper.model.path=C:/Users/kokob/whisper.cpp-master/models/ggml-base.bin
whisper.work-dir=C:/temp/whisper

# Docker will override JWT_JWKS_URI, local will use the default localhost value
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWKS_URI:http://localhost:8082/.well-known/jwks.json}
# Security logging (keep if debugging)
logging.level.org.springframework.security=TRACE

# ? REMOVE this line (it is invalid)
# audio-services/src/main/resources/public.key

# Docker compose auto-detection disabled
spring.docker.compose.enabled=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# JMX
spring.jmx.enabled=true
management.endpoints.jmx.exposure.include=*


minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket.word=${MINIO_WORD_BUCKET:wordbucket}
minio.bucket.sentence=${MINIO_SENTENCE_BUCKET:sentencebucket}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


jwt.expiration-ms=${JWT_EXPIRATION_MS}
# ===== LOCAL DB (H2 FILE) =====
spring.datasource.url=jdbc:h2:file:./data/audiodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false

# optional H2 console (local only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


