spring.application.name=audio-services
server.port=8083

# ===== DOCKER DB (POSTGRES) =====
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===== DOCKER JWKS (auth-service container) =====
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWKS_URI}

# (Don?t enable H2 console in docker)
spring.h2.console.enabled=false