port: 8083

spring:

  security:
     oauth2:
        resourceserver:
          jwt:
            jwk-set-uri=${JWT_JWKS_URI}:
  datasource:
    url: ${SPRING_DATASOURCE_URL}          # jdbc:postgresql://postgres:5432/audiodb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}

  minio:
    url: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket:
      word: wordbucket
      sentence: sentencebucket