spring.application.name=content-service

server.port=${CONTENT_SERVER_PORT:8085}

app.cors.allowed-origins=http://localhost:4200,http://10.0.0.29:4200,https://squid-striving-vantage.ngrok-free.dev

# Database
spring.datasource.url=${CONTENT_DB_URL:jdbc:h2:file:./data/contentdb}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${CONTENT_DB_USERNAME:sa}
spring.datasource.password=${CONTENT_DB_PASSWORD:}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console